# Linear Algebra for Machine Learning 📐

Linear algebra is used everywhere in ML:
neural networks, regression, PCA, deep learning.

📌 Part of: **AI/ML Roadmap – Beginner to Advanced**


In [1]:
import numpy as np


## Scalars, Vectors, and Matrices


In [2]:
scalar = 5
vector = np.array([1, 2, 3])
matrix = np.array([[1, 2], [3, 4]])

print("Scalar:", scalar)
print("Vector:", vector)
print("Matrix:\n", matrix)


Scalar: 5
Vector: [1 2 3]
Matrix:
 [[1 2]
 [3 4]]


## Vector Operations


In [3]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print("Addition:", v1 + v2)
print("Dot Product:", np.dot(v1, v2))


Addition: [5 7 9]
Dot Product: 32


## Matrix Operations


In [4]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix Multiplication:\n", np.dot(A, B))


Matrix Multiplication:
 [[19 22]
 [43 50]]


## Transpose


In [5]:
print(A.T)


[[1 3]
 [2 4]]


## Determinant


In [6]:
print("Determinant:", np.linalg.det(A))


Determinant: -2.0000000000000004


## Inverse


In [7]:
print("Inverse:\n", np.linalg.inv(A))


Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


## Why Linear Algebra is Important?


- Neural networks  
- Linear regression  
- Image processing  
- Deep learning  


## 🧪 Practice

1. Create your own matrix  
2. Find determinant  
3. Find inverse  


## ✅ Summary

You learned:
- Vectors  
- Matrices  
- Dot product  
- Determinant  
- Inverse  

➡️ Next: **Calculus**
