# NumPy Basics 🔢

NumPy (Numerical Python) is the core library for numerical computing in Python.
It is used heavily in Data Science, Machine Learning, and AI.

📌 Part of: **AI/ML Roadmap – Beginner to Advanced**


## Why NumPy?

Python lists are slow for numerical computation.
NumPy provides:
- Faster execution
- Less memory usage
- Mathematical functions
- Multi-dimensional arrays


In [1]:
import numpy as np


## Creating NumPy Arrays


In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = np.array([10, 20, 30])
print(arr2)


[1 2 3 4 5]
[10 20 30]


## Array Data Types


In [3]:
arr = np.array([1, 2, 3.5])
print(arr)
print(arr.dtype)


[1.  2.  3.5]
float64


## NumPy vs Python List


In [4]:
py_list = [1, 2, 3, 4]
np_array = np.array([1, 2, 3, 4])

print(type(py_list))
print(type(np_array))


<class 'list'>
<class 'numpy.ndarray'>


## NumPy Array Attributes


In [5]:
arr = np.array([[1,2,3],[4,5,6]])

print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data Type:", arr.dtype)


Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int64


## Common Mistakes


In [6]:
# This creates a Python list, not NumPy array
wrong = [1,2,3]

# This creates a NumPy array
correct = np.array([1,2,3])


## 🧪 Practice

1. Create a NumPy array of 10 numbers
2. Print its shape, size and data type
3. Create a 2D array


## ✅ Summary

In this notebook, you learned:
- What NumPy is
- How to create arrays
- Array attributes
- Why NumPy is better than lists

➡️ Next: **NumPy Arrays**
