# NumPy Arrays 📊

In this notebook, we will learn how to create and work with
1D, 2D, and 3D NumPy arrays.

📌 Part of: **AI/ML Roadmap – Beginner to Advanced**


In [1]:
import numpy as np


## Creating 1D Arrays


In [2]:
arr1 = np.array([10, 20, 30, 40])
print(arr1)


[10 20 30 40]


## Creating 2D Arrays


In [3]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr2)


[[1 2 3]
 [4 5 6]]


## Creating 3D Arrays


In [4]:
arr3 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

print(arr3)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Using Built-in Functions


In [5]:
zeros = np.zeros((3, 4))
ones = np.ones((2, 3))

print(zeros)
print(ones)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


## Using arange()


In [6]:
arr = np.arange(1, 11)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


## Using linspace()


In [7]:
arr = np.linspace(1, 10, 5)
print(arr)


[ 1.    3.25  5.5   7.75 10.  ]


## Reshaping Arrays


In [8]:
arr = np.arange(1, 13)
reshaped = arr.reshape(3, 4)

print(reshaped)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Random Arrays


In [9]:
rand = np.random.rand(3, 3)
print(rand)


[[0.43881138 0.81211906 0.33394298]
 [0.08589283 0.83840482 0.92389224]
 [0.97672246 0.94243348 0.06000523]]


## 🧪 Practice

1. Create a 5x5 zero matrix
2. Create an array of numbers from 10 to 50
3. Reshape an array of size 12 into (3,4)


## ✅ Summary

In this notebook, you learned:
- 1D, 2D, and 3D arrays
- zeros, ones
- arange and linspace
- reshape
- random arrays

➡️ Next: **Indexing and Slicing**
