# NumPy Indexing and Slicing 🔍

Indexing and slicing allow us to extract and modify parts of arrays.
This is extremely important in Data Science and Machine Learning.

📌 Part of: **AI/ML Roadmap – Beginner to Advanced**


In [1]:
import numpy as np


## Indexing 1D Arrays


In [2]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[2])
print(arr[-1])


10
30
50


## Slicing 1D Arrays


In [3]:
print(arr[1:4])
print(arr[:3])
print(arr[2:])
print(arr[::2])
print(arr[::-1])


[20 30 40]
[10 20 30]
[30 40 50]
[10 30 50]
[50 40 30 20 10]


## Indexing 2D Arrays


In [4]:
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr2d[0, 1])
print(arr2d[2, 2])


2
9


## Slicing 2D Arrays


In [5]:
print(arr2d[0:2, 1:3])
print(arr2d[:, 1])
print(arr2d[1, :])


[[2 3]
 [5 6]]
[2 5 8]
[4 5 6]


## Boolean Indexing


In [6]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 25])
print(arr[arr % 20 == 0])


[30 40 50]
[20 40]


## Modifying Values using Indexing


In [7]:
arr = np.array([1, 2, 3, 4, 5])

arr[0] = 100
arr[arr > 3] = 0

print(arr)


[0 2 3 0 0]


## Fancy Indexing


In [8]:
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]

print(arr[indices])


[10 30 50]


## Why Indexing is Important in ML?


- Select specific columns from dataset
- Filter rows based on condition
- Modify data for cleaning
- Prepare input for ML models


## 🧪 Practice

1. Create a 2D array of shape (4,4)
2. Extract the 2nd column
3. Extract all elements greater than 10
4. Replace all even numbers with 0


## ✅ Summary

In this notebook, you learned:
- Indexing 1D & 2D arrays
- Slicing arrays
- Boolean indexing
- Fancy indexing
- Modifying array values

➡️ Next: **NumPy Operations**
