# NumPy Operations ⚙️

NumPy allows us to perform fast mathematical and matrix operations.
These operations are heavily used in Machine Learning.

📌 Part of: **AI/ML Roadmap – Beginner to Advanced**


In [1]:
import numpy as np


## Arithmetic Operations


In [2]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)
print(a - b)
print(a * b)
print(a / b)


[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


## Scalar Operations


In [3]:
arr = np.array([1, 2, 3, 4])

print(arr + 10)
print(arr * 2)


[11 12 13 14]
[2 4 6 8]


## Mathematical Functions


In [4]:
arr = np.array([1, 4, 9, 16])

print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))


[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


## Aggregate Functions


In [5]:
arr = np.array([10, 20, 30, 40])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Std:", np.std(arr))


Sum: 100
Mean: 25.0
Max: 40
Min: 10
Std: 11.180339887498949


## Matrix Operations


In [6]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix Addition:\n", A + B)
print("Matrix Multiplication:\n", np.dot(A, B))


Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


## Transpose of a Matrix


In [7]:
print(A.T)


[[1 3]
 [2 4]]


## Comparison Operations


In [8]:
arr = np.array([10, 20, 30, 40])

print(arr > 25)
print(arr[arr > 25])


[False False  True  True]
[30 40]


## Why These Operations Matter in ML?


- Feature scaling
- Matrix multiplication for neural networks
- Statistical calculations
- Data normalization


## 🧪 Practice

1. Create two arrays and perform all arithmetic operations.
2. Find mean and standard deviation of a dataset.
3. Multiply two 2×2 matrices.


## ✅ Summary

In this notebook, you learned:
- Arithmetic & scalar operations
- Mathematical functions
- Aggregation functions
- Matrix operations

➡️ Next: **NumPy Broadcasting**
