# NumPy Broadcasting 📡

Broadcasting allows NumPy to perform operations on arrays
of different shapes without making copies of data.

This concept is extremely important in Machine Learning.

📌 Part of: **AI/ML Roadmap – Beginner to Advanced**


In [1]:
import numpy as np


## What is Broadcasting?

Broadcasting is the ability of NumPy to stretch smaller arrays
to match larger arrays during arithmetic operations.


In [2]:
arr = np.array([1, 2, 3])
print(arr + 10)


[11 12 13]


## Broadcasting with 1D and 2D Arrays


In [3]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

vector = np.array([10, 20, 30])

print(matrix + vector)


[[11 22 33]
 [14 25 36]]


## Broadcasting Rules


1. Compare shapes from right to left  
2. Dimensions must be equal or one must be 1  
3. If compatible, broadcasting happens


## Broadcasting Example (Row-wise)


In [4]:
arr = np.array([[1,2,3],
                [4,5,6]])

row = np.array([10,20,30])

print(arr + row)


[[11 22 33]
 [14 25 36]]


## Broadcasting Column-wise


In [5]:
col = np.array([[10],
                [20]])

print(arr + col)


[[11 12 13]
 [24 25 26]]


## Real ML Use Case


Broadcasting is used when:
- Adding bias to neurons
- Normalizing features
- Scaling datasets


## Common Broadcasting Error


In [6]:
# This will cause an error
# a = np.array([1,2,3])
# b = np.array([1,2])
# print(a + b)


## 🧪 Practice

1. Add a scalar to a 2D array
2. Add a vector to a matrix
3. Add a column vector to a matrix


## ✅ Summary

In this notebook, you learned:
- What broadcasting is
- Broadcasting rules
- Row-wise & column-wise broadcasting
- Why broadcasting is important in ML

➡️ Next: **NumPy Statistics**
