# NumPy in Real-World Data Science 🌍

In this notebook, we will use NumPy to work with a real-world style dataset
similar to what is used in Machine Learning.

📌 Part of: **AI/ML Roadmap – Beginner to Advanced**


In [1]:
import numpy as np


## Sample Dataset (Student Marks)

Each row represents a student  
Columns: Math, Science, English


In [2]:
marks = np.array([
    [80, 75, 90],
    [60, 70, 65],
    [85, 95, 88],
    [50, 60, 55],
    [90, 92, 85]
])

print(marks)


[[80 75 90]
 [60 70 65]
 [85 95 88]
 [50 60 55]
 [90 92 85]]


## Average Marks of Each Student


In [3]:
student_avg = np.mean(marks, axis=1)
print("Student Averages:", student_avg)


Student Averages: [81.66666667 65.         89.33333333 55.         89.        ]


## Average Marks of Each Subject


In [4]:
subject_avg = np.mean(marks, axis=0)
print("Subject Averages:", subject_avg)


Subject Averages: [73.  78.4 76.6]


## Find Top Performer


In [5]:
top_student = np.argmax(student_avg)
print("Top student index:", top_student)
print("Top student average:", student_avg[top_student])


Top student index: 2
Top student average: 89.33333333333333


## Students Who Passed (Average ≥ 70)


In [6]:
passed = student_avg >= 70
print("Passed:", passed)


Passed: [ True False  True False  True]


## Filtering Passed Students


In [7]:
passed_students = marks[passed]
print(passed_students)


[[80 75 90]
 [85 95 88]
 [90 92 85]]


## Normalizing Data (Feature Scaling)


In [8]:
min_vals = np.min(marks, axis=0)
max_vals = np.max(marks, axis=0)

normalized = (marks - min_vals) / (max_vals - min_vals)
print(normalized)


[[0.75       0.42857143 1.        ]
 [0.25       0.28571429 0.28571429]
 [0.875      1.         0.94285714]
 [0.         0.         0.        ]
 [1.         0.91428571 0.85714286]]


## Why This Matters in Machine Learning?


- Feature scaling improves model performance  
- Filtering is used to clean datasets  
- Statistics help detect patterns  
- NumPy arrays feed ML models


## 🧪 Practice

1. Add one more student to dataset  
2. Find the student with lowest average  
3. Normalize a new dataset  
4. Find subject with highest average  


## ✅ Summary

In this notebook, you learned:
- How NumPy is used on real data
- Row-wise and column-wise analysis
- Filtering and indexing
- Feature normalization

🎉 You have completed **NumPy**!

➡️ Next: **Pandas – Data Analysis**
